version: '3.8'
services:
  node1:
    build: .
    container_name: node1
    networks:
      - mpi_network

  node2:
    build: .
    container_name: node2
    networks:
      - mpi_network

  node3:
    build: .
    container_name: node3
    networks:
      - mpi_network

networks:
  mpi_network:
    driver: bridge